version: '3.8'

services:
  bookmarker-api:
    image: harivara/bookmaker-api:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://bookmarker-db:5432/appdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "18080:8081"     # exposed host:container
    restart: always
    depends_on:
      - bookmarker-db

  bookmarker-ui-nextjs:
    container_name: bookmarker-ui-netjs
    build:
      context: bookmarker-ui-nextjs
      dockerfile: Dockerfile
    ports:
      - "13000:3000"
    environment:
      SERVER_SIDE_API_BASE_URL: http://bookmarker-api:8081
      CLIENT_SIDE_API_BASE_URL: http://localhost:18080